### ISSUE TITLE
build/make/core/base_rules.mk:324: error: system/core/rootdir: MODULE.TARGET.ETC.init.rc already defined by device/samsung/m21/rootdir.

### ISSUE THREAD

**Issue by dkey21** [sebaubuntu-python/aospdtgen#26]
I created the device tree from your scripts. I created the vendor with AndroidDumps/dumpyara. Can you show me the way to fish?

Device tree: https://github.com/exynos-9611/android_device_samsung_m21
Kernel: https://github.com/exynos-9611/android_kernel_samsung_m21
Vendor: https://gitlab.com/exynos-9611/proprietary_vendor_samsung
Manifests: https://github.com/exynos-9611/local_manifests

Dumpyara:
M215FXXU2ATJ5 (A10): https://gitlab.com/dkey21/samsung-m21-dump-m215fxxu2atj5
M215FXXS2BUK2 (A11): https://gitlab.com/dkey21/samsung-m21-dump-m215fxxs2buk2
M215FXXU2CVCC (A12): https://gitlab.com/dkey21/samsung-m21-dump-m215fxxu2cvcc

Samsung Open Source: https://github.com/exynos-9611/samsung_m21/releases/tag/opensource

**Comment by dkey21** [comment]
``============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
LINEAGE_VERSION=17.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200805.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21
============================================
[ 62% 405/647] including packages/apps/Backgrounds/Android.mk ...
/bin/bash: line 0: test: -gt: unary operator expected
[ 79% 513/647] including system/core/rootdir/Android.mk ...
FAILED:
build/make/core/base_rules.mk:324: error: system/core/rootdir: MODULE.TARGET.ETC.init.rc already defined by device/samsung/m21/rootdir.
11:37:54 ckati failed with: exit status 1

#### failed to build some targets (03:29 (mm:ss)) ####

**Comment by dkey21** [comment]
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
LINEAGE_VERSION=17.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200805.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21
============================================
[ 62% 405/647] including packages/apps/Backgrounds/Android.mk ...
/bin/bash: line 0: test: -gt: unary operator expected
[ 79% 513/647] including system/core/rootdir/Android.mk ...
FAILED:
build/make/core/base_rules.mk:324: error: system/core/rootdir: MODULE.TARGET.ETC.init.rc already defined by device/samsung/m21/rootdir.
11:37:54 ckati failed with: exit status 1

#### failed to build some targets (03:29 (mm:ss)) ####

**Comment by dkey21** [comment]
> ============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
LINEAGE_VERSION=17.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200805.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21
============================================
[ 62% 405/647] including packages/apps/Backgrounds/Android.mk ...
/bin/bash: line 0: test: -gt: unary operator expected
[ 79% 513/647] including system/core/rootdir/Android.mk ...
FAILED:
build/make/core/base_rules.mk:324: error: system/core/rootdir: MODULE.TARGET.ETC.init.rc already defined by device/samsung/m21/rootdir.
11:37:54 ckati failed with: exit status 1

#### failed to build some targets (03:29 (mm:ss)) ####

**Comment by dkey21** [comment]
> ============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
LINEAGE_VERSION=18.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ3A.211001.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21 packages/apps/Bluetooth
============================================
[ 99% 441/442] finishing build rules ...
FAILED:
In file included from build/make/core/main.mk:1341:
build/make/core/Makefile:49: error: VINTF metadata found in PRODUCT_COPY_FILES: vendor/samsung/m21/proprietary/odm/etc/vintf/manifest_disabled.xml:system/vendor/odm/etc/vintf/manifest_disabled.xml, use ODM_MANIFEST_FILES / vintf_fragments instead!.
12:55:28 ckati failed with: exit status 1

#### failed to build some targets (07:42 (mm:ss)) ####

**Comment by SebaUbuntu** [comment]
Build 19.1 and reextract vendor with extract-utils

**Comment by dkey21** [comment]
> ============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
LINEAGE_VERSION=19.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SQ3A.220705.004
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21 packages/apps/Bluetooth
============================================
[ 93% 447/479] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
[ 99% 478/479] finishing build rules ...
FAILED:
In file included from build/make/core/main.mk:1441:
build/make/core/Makefile:61: error: VINTF metadata found in PRODUCT_COPY_FILES: vendor/samsung/m21/proprietary/odm/etc/vintf/manifest_disabled.xml:system/vendor/odm/etc/vintf/manifest_disabled.xml, use ODM_MANIFEST_FILES / vintf_fragments instead!.
15:28:54 ckati failed with: exit status 1

#### failed to build some targets (16:53 (mm:ss)) ####

**Comment by SebaUbuntu** [comment]
You didn't reextract vendor, it should add automatically VINTF fragments as Soong modules

**Comment by dkey21** [comment]
> ============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
LINEAGE_VERSION=19.1-20220823-UNOFFICIAL-m21
TARGET_PRODUCT=lineage_m21
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-122-generic-x86_64-Ubuntu-20.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SQ3A.220705.004
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/samsung/m21 vendor/samsung/m21 packages/apps/Bluetooth
============================================
============================================
vendor/samsung/m21/m21-vendor.mk was modified, regenerating...
[ 97% 1220/1252] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
[ 99% 1251/1252] finishing build rules ...
FAILED:
In file included from build/make/core/main.mk:1441:
build/make/core/Makefile:61: error: VINTF metadata found in PRODUCT_COPY_FILES: vendor/samsung/m21/proprietary/odm/etc/vintf/manifest_disabled.xml:system/vendor/odm/etc/vintf/manifest_disabled.xml, use ODM_MANIFEST_FILES / vintf_fragments instead!.
16:07:51 ckati failed with: exit status 1

#### failed to build some targets (14:54 (mm:ss)) ####


$ rm -r vendor/samsung/m21
$ source build/envsetup.sh
$ breakfast m21
$ cd device/samsung/m21
$ ./extract-files.sh ~/dumpyara/working/Samfw.com_SM-M215F_TUR_M215FXXU2CVCC_fac
$ croot
$ brunch m21

**Comment by dkey21** [comment]
M215FXXU2CVCC (A12), M215FXXS2BUK2 (A11), M215FXXU2ATJ5 (A10)
I tried three different versions for lineage 19.1 but it gives the same error.

Samsung Open Source platform and kernel: https://github.com/exynos-9611/samsung_m21/releases/tag/opensource

**Comment by SebaUbuntu** [comment]
Due to cringe behaviour, I'm closing this issue

**Comment by dkey21** [comment]
Why support only one device on the same platform when multiple devices can be supported? not cringe behavior  ●︿● ⋋_⋌

DTS:
https://github.com/exynos-9611/android_kernel_samsung_m21/tree/lineage-19.1/arch/arm64/boot/dts/samsung
Example:
https://github.com/LineageOS/android_kernel_samsung_universal7580/tree/lineage-18.1/arch/arm64/configs
https://github.com/erfanoabdi/android_device_samsung_universal9610-common
