### ISSUE TITLE
What could be some sort of default config.fs that we can come up with?

### ISSUE THREAD

**Issue by sultanahamer** [sebaubuntu-python/aospdtgen#31]
Hi There,

I have used this tool to generate device tree and building lineageos 18.0

Its done till 70% and had 3 errors until now. Fixed them. Currently stuck at not having default config.fs which declares the users like this
https://github.com/LineageOS/android_device_sony_tama-common/blob/lineage-19.1/config.fs

I have found my device's /etc/passwd file non empty so I can create those users as I found from that file. But having this auto generated is a really good step that we can automate is what I felt.

Let me know about your views on this. If I am able to successfully build lineageos and use it then I will create a documentation/video series explaining how to build lineageos for a device with aospdtgen given they have dump from dumpyara

In case either you or someone have already created such documenation/video series explaining how to build androidos using this(aospdtgen) and dumpyara, please link me to it. I can add the errors I face in case they are not covered in that documentation.

**Comment by SebaUbuntu** [comment]
https://github.com/LineageOS/scripts/tree/master/config-fs-gen

It isn't possible to automate this since AOSP headers are needed
