### ISSUE TITLE
There are some data after the end of the payload data

### ISSUE THREAD

**Issue by Boom-Hacker** [sebaubuntu-python/aospdtgen#71]
beforespace@beforespace-desktop:~$ python3 -m dumpyara '/media/beforespace/HDD/androidhacking/k40s/miui_MUNCH_V14.0.9.0.TLMCNXM_596329468b_13.0.zip' 
Dumpyara
Version 1.0.5

[INFO] Step 1 - Extracting archive
[INFO] Pattern .*\.tar\.md5 not found
[INFO] Step 2 - Preparing partition images
[INFO] Found multipartition image: payload.bin
Extracting 'abl.img'
Extracting 'aop.img'
Extracting 'bluetooth.img'
Extracting 'boot.img'
Extracting 'cmnlib.img'
Extracting 'cmnlib64.img'
Extracting 'devcfg.img'
Extracting 'dsp.img'
Extracting 'dtbo.img'
Extracting 'featenabler.img'
Extracting 'hyp.img'
Extracting 'imagefv.img'
Extracting 'keymaster.img'
Extracting 'modem.img'
Extracting 'odm.img'
Extracting 'product.img'
Extracting 'qupfw.img'
Extracting 'system.img'
Extracting 'system_ext.img'
Extracting 'tz.img'
Extracting 'uefisecapp.img'
Extracting 'vbmeta.img'
Extracting 'vbmeta_system.img'
Extracting 'vendor.img'
Extracting 'vendor_boot.img'
Extracting 'xbl.img'
Extracting 'xbl_config.img'
Extracting 'mi_ext.img'
[INFO] Pattern super(?!.*(_empty)).*\.img not found
[INFO] Step 3 - Extracting partitions
[INFO] Extracting boot
[INFO] Cloning AIK...
[INFO] Extracting dtbo
[INFO] Extracting vendor_boot
[INFO] Cloning AIK...
[INFO] Extracting tz
[INFO] Extracting odm
[INFO] Extracting product
[INFO] Extracting system
[INFO] Extracting system_ext
[INFO] Extracting vendor
[INFO] Extracting modem
[ERROR] Error extracting modem.img
[ERROR] 
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,64 bits,36 CPUs Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (306F2),ASM,AES-NI)

Scanning the drive for archives:
1 file, 282112000 bytes (270 MiB)

Extracting archive: /home/beforespace/miui_MUNCH_V14.0.9.0.TLMCNXM_596329468b_13.0/temp_raw_images/modem.img

ERRORS:
Unexpected end of archive

--
Path = /home/beforespace/miui_MUNCH_V14.0.9.0.TLMCNXM_596329468b_13.0/temp_raw_images/modem.img
Type = FAT
ERRORS:
Unexpected end of archive
Physical Size = 469762048
File System = FAT16
Cluster Size = 16384
Free Space = 187645952
Headers Size = 8843264
Sector Size = 4096
ID = 12345678

ERROR: Data Error : image/modem_pr/mcfg/configs/mcfg_hw/oem_hw_null.txt
ERROR: Data Error : image/modem_pr/mcfg/configs/mcfg_sw/oem_sw_null.txt

Sub items Errors: 2

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 2

[INFO] Step 4 - Finalizing
[INFO] Creating all_files.txt

Done! You can find the dump in /home/beforespace/miui_MUNCH_V14.0.9.0.TLMCNXM_596329468b_13.0

**Comment by SebaUbuntu** [comment]
It's normal
