### ISSUE TITLE
build/make/core/base_rules.mk:324: error: system/core/rootdir: MODULE.TARGET.ETC.init.rc already defined by device/samsung/j3y17lte/rootdir.

### ISSUE THREAD

**Issue by magnoliy** [sebaubuntu-python/aospdtgen#78]
Build 19.1 and reextract vendor with extract-utils

_Originally posted by @SebaUbuntu in https://github.com/sebaubuntu-python/aospdtgen/issues/26#issuecomment-1224045895_
            
my phone only has android 9. what do i do then? i am building 10, because the tree wont work on 9. i redid the vendor and nothing changed.

**Comment by SebaUbuntu** [comment]
This tool requires some basic AOSP build system knowledge, can't help with that
