### ISSUE TITLE
[WARNING] Unknown HAL type native          what is this? 

### ISSUE THREAD

**Issue by Become-ILLUSORY** [sebaubuntu-python/aospdtgen#83]
Will this have any impact?

**Comment by Become-ILLUSORY** [comment]
Android device tree generator
Version 1.1.1

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
[INFO] Parsing build props and device info
[INFO] Parsing fstab
[INFO] Extracting boot image
[INFO] Cloning AIK...
[INFO] Cloning AIK...
[INFO] Getting list of rootdir files
[INFO] Generating proprietary files list

Done! You can find the device tree in devicetree

**Comment by SebaUbuntu** [comment]
Nothing to worry about
